language: android
sudo: false
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    #- build-tools-19.1.0
    - 30.0.2

    # The SDK version used to compile your project
    - android-29

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- 'system-imgages;android-29;google_apis;x86_64'
    #- 'system-images;android-29;default;x86_64'

before_install:
 - chmod +x ./gradlew

# Emulator Management: Create, Start and Wait
before_script:

script: ./gradlew clean build 
