language: android
sudo: false
android:
  components:
    # Build tools available on travis-ci 04/12/2021
    # - build-tools-30.0.0-preview
    - build-tools-29.0.3

    # The SDK version in use with checkers
    - android-29

before_install:
 - chmod +x ./gradlew

# Emulator Management: Create, Start and Wait
before_script:
   # The checkers project use build-tools-30.0.2. Gradle 3.0.0+ will download any SDK in. However, license agreement applies. 
   - echo yes | sdkmanager 'tools' 'platform-tools' 'system-images;android-24;default;armeabi-v7a' 'system-images;android-24;default;x86_64'
   - sdkmanager --list
   - whereis emulator
   - find ./ -type d -name 'emulator' -print
   - echo no  | avdmanager create avd --force -n test --tag default --abi x86_64 --package 'system-images;android-24;default;x86_64'
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - adb shell input keyevent 82 &

# Auto-download missing packages with Gradle
#
# When you run a build from the command line, or when using Android Studio 3.3 or later, 
# Gradle can automatically download missing SDK packages that a project depends on, as long as 
# the corresponding SDK license agreements have already been accepted using the SDK Manager.
#
# When you accept the license agreements using the SDK Manager, Android Studio creates a licenses 
# directory inside the SDK home directory. This licenses directory is necessary for Gradle to 
# auto-download missing packages. 
#
# https://bit.ly/2PZhGQr
script: ./gradlew clean build 
