language: android
sudo: false
android:
  components:
    # The SDK version used to compile your project
    #- android-29

before_install:
 - chmod +x ./gradlew

# Emulator Management: Create, Start and Wait
before_script:
 - echo yes | sdkmanager 'system-images;android-29;google_apis;x86_64' 'build-tools;30.0.2' 'tools' 'platform-tools'

script: ./gradlew clean build connectedDebugAndroidTest
