name: 'Android: Checkers'
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Java SDK
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'oracle'
      - run: sdkmanager --yes 'build-tools-35.0.0' 'platform;android-33'
      - run: ./gradlew clean build
