name: 'Android: Checkers'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: wget https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
      - run: unzip commandlinetools-linux-13114758_latest.zip
      - run: rm commandlinetools-linux-13114758_latest.zip
      - run: export ANDROID_HOME=$(pwd) && echo yes | ./cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME 'build-tools;35.0.0' 'platforms;android-35'
      - run: export ANDROID_HOME=$(pwd) && ./gradlew clean build
